### ISSUE TITLE
MongoError: Topology closed warning when running server tests

### ISSUE THREAD

**Issue by DustinAlandzes** [haylords1337/ShiftRescue#11]
```
$ npm run test

> shiftrescue@0.1.0 test /home/travis/build/haylords1337/ShiftRescue

> npm run test-server && npm run test-client

> shiftrescue@0.1.0 test-server /home/travis/build/haylords1337/ShiftRescue

> jest --runInBand

(node:5821) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

 PASS  server/app.test.js

  Login Endpoint

    ✓ should give me unauthorized if I try logging in with bad credentials (45ms)

console.error node_modules/jest-jasmine2/build/jasmine/Env.js:289

    Unhandled error

console.error node_modules/jest-jasmine2/build/jasmine/Env.js:290

    MongoError: Topology closed

        at NativeTopology.close (/home/travis/build/haylords1337/ShiftRescue/node_modules/mongodb/lib/core/sdam/topology.js:325:38)

        at /home/travis/build/haylords1337/ShiftRescue/node_modules/mongodb/lib/mongo_client.js:267:21

        at maybePromise (/home/travis/build/haylords1337/ShiftRescue/node_modules/mongodb/lib/utils.js:719:3)

        at MongoClient.Object.<anonymous>.MongoClient.close (/home/travis/build/haylords1337/ShiftRescue/node_modules/mongodb/lib/mongo_client.js:248:10)

        at /home/travis/build/haylords1337/ShiftRescue/node_modules/mongoose/lib/connection.js:711:20

        at new Promise (<anonymous>)

        at NativeConnection.Object.<anonymous>.Connection.openUri (/home/travis/build/haylords1337/ShiftRescue/node_modules/mongoose/lib/connection.js:709:19)

        at Mongoose.connect (/home/travis/build/haylords1337/ShiftRescue/node_modules/mongoose/lib/index.js:335:15)

        at Object.<anonymous> (/home/travis/build/haylords1337/ShiftRescue/server/app.test.js:30:18)

        at processTicksAndRejections (internal/process/task_queues.js:97:5)

POST /auth/login 403 22.086 ms - 12

Test Suites: 1 passed, 1 total

Tests:       1 passed, 1 total

Snapshots:   0 total

Time:        1.806s

Ran all test suites.

```

**Comment by DustinAlandzes** [comment]
will be fixed when this pr is merged: https://github.com/haylords1337/ShiftRescue/pull/13
